# Generated by Django 2.2.9 on 2023-04-03 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentid', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('virtual_wallet_balance', models.DecimalField(decimal_places=2, max_digits=8)),
                ('Department_name', models.CharField(max_length=50)),
                ('semester', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=200)),
                ('mobileno', models.CharField(max_length=20)),
            ],
        ),
    ]
