# Generated by Django 2.2.9 on 2023-04-04 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20230404_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.IntegerField(default=0),
        ),
    ]
