# Generated by Django 4.2 on 2023-04-07 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_student_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentEncoding',
            fields=[
                ('encoding_id', models.AutoField(primary_key=True, serialize=False)),
                ('encoding_data', models.TextField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
        ),
    ]
