# Generated by Django 4.2 on 2023-04-08 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_rename_student_studentencoding_studentid'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentImage',
            fields=[
                ('faceid', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='student_images/')),
                ('studentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
        ),
        migrations.DeleteModel(
            name='StudentEncoding',
        ),
    ]
