# Generated by Django 4.2 on 2023-04-09 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_studentimage_delete_studentencoding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentimage',
            name='image',
            field=models.ImageField(default='', upload_to='studentimages/'),
        ),
    ]
