# Generated by Django 3.2.18 on 2023-05-02 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_cart'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cart',
            table=None,
        ),
    ]
