# Generated by Django 3.2.18 on 2023-05-03 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_cart_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderid', models.AutoField(primary_key=True, serialize=False)),
                ('order_time', models.DateTimeField()),
                ('order_mode', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], max_length=7)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('item1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_item1', to='accounts.menuitem')),
                ('item2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_item2', to='accounts.menuitem')),
                ('item3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_item3', to='accounts.menuitem')),
                ('item4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_item4', to='accounts.menuitem')),
                ('item5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_item5', to='accounts.menuitem')),
                ('studentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
        ),
    ]
