# Generated by Django 3.2.18 on 2023-05-05 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=255)),
                ('rating', models.IntegerField()),
                ('submission_time', models.DateTimeField()),
                ('itemid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.menuitem')),
                ('studentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
        ),
    ]
